### ISSUE TITLE
Linux: abrir Pharo2.0-portable.sh

### ISSUE THREAD

**Issue by Garabito** [epernia/IDE4PLC-LPC17xx#2]
Hola, he querido aprender sobre esto y me he topado con algunos inconvenientes. 
- ¿Donde se encuentra el archivo "Linux: abrir Pharo2.0-portable.sh" que indica el README?
- ¿Cual es el archivo principal para editar y modificar el codigo con el Pharo?
Saludos

**Comment by epernia** [comment]
Buen día Carlos, este repositorio es bastante antiguo. El repositorio más actualizado de IDE4PLC es: https://github.com/ciaa/IDE4PLC

Por otro lado, no hay archivos de código fuente en Pharo, el código está embebido en la imagen. 
En estes repositorio están todas las clases del proyecto extraidas como archivos .st, el IDE está programado en lenguaje Smalltalk.
Dentro del mismo IDE puede ver todos los archivos fuente. 

Para evitar todas las complicaciones de instalación de este y otros programas dle proyecto CIAA creamos con Martín Ribelotta unos paquetes de software más sencillos de descarga e instalar que tiene todas las herramientas necesarias: y recomiendo descargar la última versión de aquí:  https://github.com/epernia/software/releases/tag/r1.1.0

Por favor lea atentamente el readme: https://github.com/epernia/software

**Comment by Garabito** [comment]
Muchas gracias, voy a revisarlo, esta muy interesante este proyecto, y
quiero ir empapandome de esta informacion.

Muchisimas gracias
Carlos Moran G.
